version: "3.8"

services:
  # ---------- ACCOUNT SERVICE ----------
  account:
    build:
      context: .
      dockerfile: account/app.dockerfile
    depends_on:
      - account_db
    environment:
      DATABASE_URL: postgres://postgres:postgres@account_db:5432/account?sslmode=disable
    restart: on-failure

  account_db:
    build:
      context: account
      dockerfile: db.dockerfile
    environment:
      POSTGRES_DB: account
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    restart: unless-stopped


  # ---------- CATALOG SERVICE ----------
  catalog:
    build:
      context: .
      dockerfile: catalog/app.dockerfile
    depends_on:
      - catalog_db
    environment:
      DATABASE_URL: http://catalog_db:9200
    restart: on-failure

  catalog_db:
    image: elasticsearch:7.17.18
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"


    # ---------- ORDER SERVICE ----------
  order:
    build:
      context: .
      dockerfile: order/app.dockerfile
    depends_on:
      - order_db
      - account
      - catalog
    environment:
      DATABASE_URL: postgres://postgres:postgres@order_db:5432/order?sslmode=disable
      ACCOUNT_SERVICE_URL: account:8080
      CATALOG_SERVICE_URL: catalog:8080
    restart: on-failure

  order_db:
    build:
      context: order
      dockerfile: db.dockerfile
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    restart: unless-stopped


  # ---------- GRAPHQL GATEWAY ----------
  graphql:
    build:
      context: .
      dockerfile: graphql/app.dockerfile
    ports:
      - "8000:8080"
    depends_on:
      - account
      - catalog
      - order
    environment:
      ACCOUNT_SERVICE_URL: account:8080
      CATALOG_SERVICE_URL: catalog:8080
      ORDER_SERVICE_URL: order:8080
    restart: on-failure

